### ISSUE TITLE
Posit text could be colored to show different fields, or show values (or something else)

### ISSUE THREAD

**Issue by mara-kr** [gussmith23/posit-bisection-viz#11]

**Comment by gussmith23** [comment]
Agreed, I think we should do the following:
- Show the posit value (should be easy)
- Color the different fields---see the [Beating Floating Point...](http://www.johngustafson.net/pdfs/BeatingFloatingPoint.pdf) paper for a color scheme (the amber, blue, and red)

**Comment by mara-kr** [comment]
Maybe have a button to switch between the two? It seems like it'd be hard to fit everything
