### ISSUE TITLE
The final word on n and es limits

### ISSUE THREAD

**Issue by gussmith23** [gussmith23/posit-bisection-viz#15]
As I stated, n and es don't actually depend on each other---that was my mistake. So we should let our viz range over:
2 <= n <= 10
0 <= es <= 10 (note that the upper range on es is NOT limited by the upper limit of n; es can be bigger than n)

(10 is arbitrary, and is frankly probably too big -- 8 is fine too)

**Comment by mara-kr** [comment]
b3f1efc
