### ISSUE TITLE
Posit text is clipping for larger n values

### ISSUE THREAD

**Issue by HelloKayT** [gussmith23/posit-bisection-viz#19]
Related to #13 but more pressing, because of usability. When the posit label gets up to ~6 characters, the end digits are clipped off on the right side.

**Comment by HelloKayT** [comment]
Text no longer clips on the right side. Instead, labels at the top and bottom of the circle overlap

**Comment by gussmith23** [comment]
i wonder if we could angle the text so that it shoots out in rays from the center of the circle, if that makes sense? like the petals of a sunflower

**Comment by mara-kr** [comment]
My thought was to add tooltips and display fewer values so we can say "details on demand" in the writeup, this would also probably fix #13

**Comment by mara-kr** [comment]
The sunflower visualization's a nice idea, but I'm finding it a bit annoying to work with? Does someone else want to give it a try?
https://stackoverflow.com/questions/17226206/d3-js-how-to-rotate-text-on-a-path

**Comment by dpetrisko** [comment]
I was trying earlier and could only get some weird spiral effect. I’ll keep trying when I get home though

**Comment by gussmith23** [comment]
This is kind of fixed with the rotation of the text. Good enough! Can always add margins if this problem pops up later.
