### ISSUE TITLE
ES slider is not intuitive

### ISSUE THREAD

**Issue by gussmith23** [gussmith23/posit-bisection-viz#31]
There are a number of comments about this.

- In the initial setting of n, the es slider doesn't actually cause any changes in the bits view.
- One user suggested graying out the "invalid" values of es -- however, there are no "invalid" values! This comment makes me realize that the explanation of es should be clearer. The suggestion specifically was to gray out values that wouldn't change the colors in the bitstring; however, the decimal representation of the number changes, even if the colors in the bitstring doesn't change.

So we need to figure out how to indicate that the change in es is changing the number, even if the "bits" view remains unchanged.

- Make the slider blue? So that it relates to the exponent bits?

**Comment by mara-kr** [comment]
Set default to an example where changing ES changing something and add to the description

**Comment by mara-kr** [comment]
The Linear view and log view show this pretty well, points actually move around with changing values of ES
