### ISSUE TITLE
Hard to notice changes in bitstring view

### ISSUE THREAD

**Issue by gussmith23** [gussmith23/posit-bisection-viz#34]
Users are

1. unclear on when to expect changes in the bitstring view (at some settings of n, changing es doesn't change the bitstring, see #31) 
2. not satisfied with the changes when they happen -- they're not apparent enough sometimes

> What if a different encoding could be used to draw attention to the different bits of interest? Currently, it takes a lot of interaction and attention to notice changes.

**Comment by soctar** [comment]
LUT based on N? There's also a way to go to scientific notion in JS

**Comment by gussmith23** [comment]
If it's hard to highlight individual bits flipping, you can ignore this.
