### ISSUE TITLE
Sliders need to be centered

### ISSUE THREAD

**Issue by mara-kr** [gussmith23/posit-bisection-viz#4]
Buttons to change n and es should be in the center of the view

The tutorial looks like they're placing buttons in a separate frame below the chart, that might be a better approach than referring to HTML buttons

**Comment by soctar** [comment]
The tutorial looks like they're placing buttons in a separate frame below the chart, that might be a better approach than referring to HTML buttons

**Comment by dpetrisko** [comment]
Agreed on the use d3 frame instead of html thing

**Comment by HelloKayT** [comment]
Sliders are centered now, although I don't know that they're quite right still, so I'll leave this open for now

**Comment by mara-kr** [comment]
Specifically, resizing the window width-wise at some point puts the visualization to the right of the sliders

**Comment by HelloKayT** [comment]
I think it's because the sliders are in a table and the center of the table is aligned to the center of the page rather than the center of the cell of the table that has the sliders. No idea how to fix that
