### ISSUE TITLE
Document all functions you wrote

### ISSUE THREAD

**Issue by gussmith23** [gussmith23/posit-bisection-viz#40]
We can do this during our hackathon

**Comment by gussmith23** [comment]
See `drawProjectiveRealsLine` for an example of a Javascript docstring format. Feel free to imitate that for consistency, but it's really not important if you do. It's more important to clearly explain what each function takes/returns/does.

**Comment by mara-kr** [comment]
All the stuff in `viz.js` is done, so imma take Katie and I off of this
