### ISSUE TITLE
`contianer` typo

### ISSUE THREAD

**Issue by gussmith23** [gussmith23/posit-bisection-viz#41]
https://github.com/gussmith23/posit-bisection-viz/blob/ec0d4598a231e01df982042d0a352b69388b5b34/viz.js#L10

**Comment by gussmith23** [comment]
How does this not break the code lol

**Comment by gussmith23** [comment]
It appears in one other place too.

**Comment by mara-kr** [comment]
We're explicitly passing the container as a global now -- `svg_viz_container`
