### ISSUE TITLE
How can you support selecting/scrubbing in d3?

### ISSUE THREAD

**Issue by gussmith23** [gussmith23/posit-bisection-viz#43]
This is easy in Vega, but likely will take a lot of work in d3. We need to look at examples and plan this out so that the code doesn't get too messy (because it'll take a lot of code!)

**Comment by HelloKayT** [comment]
Basic brush examples: https://www.d3-graph-gallery.com/graph/interactivity_brush.html
Circular brush examples:
http://bl.ocks.org/emeeks/ccc0368f6fb127d60b7c
http://bl.ocks.org/emeeks/5850fa6583bfd90e7899
