### ISSUE TITLE
IEEE float library

### ISSUE THREAD

**Issue by gussmith23** [gussmith23/posit-bisection-viz#49]
Need a float library with a similar feature set to the posit library.

**Comment by gussmith23** [comment]
- Rounding boxes
- Should we just start with 32 bit? 16 bit?

**Comment by gussmith23** [comment]
Coming back to this, I'm thinking we should actually compare posit8/16 with float16 and bfloat16. These would be useful comparison points, and doable in Javascript.

**Comment by dpetrisko** [comment]
Added float16 and bfloat16 library analog to posit library (although much simpler). I'm not exactly sure what fields are needed by the viz library, but I return:
return {
pos: positiveFloat,
neg: negativeFloat,
zero: zeroFloat,
inf: infinity
}

There's also a bunch of NaNs, but they just get filtered out at this step

**Comment by dpetrisko** [comment]
I'm also unsure of the bounding box computation
