### ISSUE TITLE
It doesn't make sense to brush past infinity in either direction

### ISSUE THREAD

**Issue by gussmith23** [gussmith23/posit-bisection-viz#56]
Having a brush that selects -maxposit, infinity, and maxposit doesn't really make much logical sense to plot on a straight number line.

Can we limit the brush so that neither end can pass infinity? @HelloKayT

**Comment by HelloKayT** [comment]
Fixed, I think

**Comment by HelloKayT** [comment]
Apparently not fixed if you drag aggressively

**Comment by HelloKayT** [comment]
Actually fixed now I hope
