### ISSUE TITLE
Viz breaks with large value of ES

### ISSUE THREAD

**Issue by gussmith23** [gussmith23/posit-bisection-viz#57]
Multiple errors related to the fact that the numbers get so large that they can't be represented in 64 bit floats.

**Comment by gussmith23** [comment]
Not really sure how to fix this other than: we can check which values of (n, es) will produce numbers larger than the max 64bit float and block other settings.

(We can just have a function that computes all of the possible settings)

**Comment by mara-kr** [comment]
ES Max =7
