### ISSUE TITLE
The arrowheads collide at the top of the arc!

### ISSUE THREAD

**Issue by mara-kr** [gussmith23/posit-bisection-viz#8]
I think we just want some spacing at the top of the circle for the arrow heads, but this should be nice when we have a large number of posits in the circle.

**Comment by dpetrisko** [comment]
I tried fixing this, but then the posit angles get screwed up (since they're distributed evenly across 350 degrees).  Possibly a solution is to have the posits on an invisible line and have the arrows drawn separately with a buffer

**Comment by mara-kr** [comment]
Did you just try changing the formula for ntheta to be `175/(1 << (n-1)`?

**Comment by dpetrisko** [comment]
function generateArcFromPosit(x_center, y_center, radius, dtheta, sign, posit) {
    var posit_as_int, start_angle, end_angle;
    var infinity = 4;
    // draw arcs in the positive direction
    var posit_as_int = unsignedIntegerFromBitstring(posit.bitstring);
    var infVal = 2**(posit.bitstring.length - 1);

    var arrowHeadBuffer = 5;
    if (sign === 0) {
        start_angle = 180 - (dtheta * (posit_as_int - 1)) + arrowHeadBuffer
        end_angle = 180 - (dtheta * posit_as_int) + arrowHeadBuffer
    } else {
        // Semi-hacky correction so that negative posits go
        // from most negative to least negative
        if (posit.value != Infinity) { posit_as_int -= infVal;}
        start_angle = 180 + (dtheta * (posit_as_int - 1)) - arrowHeadBuffer
        end_angle = 180 + (dtheta * (posit_as_int)) - arrowHeadBuffer
    }
    return describeArc(x_center, y_center, radius, sign, start_angle, end_angle)
}

**Comment by dpetrisko** [comment]
This correctly has the tips of the arrows touching, but the distribution is wonky

**Comment by gussmith23** [comment]
Hey all, i think there's an easier solution to this:
```html
<marker id="arrowhead" markerWidth="10" markerHeight="10" refX="8" refY="3" orient="auto" markerUnits="strokeWidth"><path d="M0,0 L0,6 L9,3 z" fill="black"></path></marker>
```
I changed `refX` to 8 here with good results:
![Uploading Screen Shot 2019-05-03 at 9.48.26 PM.png…]()

**Comment by gussmith23** [comment]
<img width="528" alt="Screen Shot 2019-05-03 at 9 48 26 PM" src="https://user-images.githubusercontent.com/1203329/57174077-953d2580-6ded-11e9-9419-a2cbf41ed8f1.png">

**Comment by gussmith23** [comment]
This anchors the front (ish) of the arrowhead to the end of the line, instead of anchoring the back of the arrowhead. Check out the `<marker>` docs.

**Comment by mara-kr** [comment]
Thanks gus! b3f1efc
